version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  delta-context:
    image: semtech/mu-javascript-template
    ports:
      - 8888:80
      - 9229:9229
    environment:
      NODE_ENV: "development"
    links:
      - db:database
    volumes:
      - ./:/app/
  triplestore:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/db/virtuoso.ini:/data/virtuoso.ini
    restart: always
    logging: *default-logging
  db:
    image: semtech/mu-authorization:feature-service-roam-r1
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      LOG_INCOMING_SPARQL_QUERIES: "true"
      LOG_ACCESS_RIGHTS: "true"
      LOG_OUTGOING_SPARQL_QUERY_ROUNDTRIP: "true"
      ERROR_ON_UNWRITTEN_DATA: "true"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
